backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: settings
    label: Impostazioni
    files:
      - file: settings.json
        label: Impostazioni sito
        name: settings
        fields:
          - { label: "Telefono WhatsApp (internazionale, es. 39345...)", name: "whatsapp_phone", widget: "string", default: "" }
          - { label: "Tariffa partner €/h", name: "partner_hourly", widget: "number", value_type: "float", step: 0.1, default: 14.2 }
          - { label: "Tariffa cliente €/h", name: "client_hourly", widget: "number", value_type: "float", step: 0.1, default: 22 }

  - name: houses
    label: Case
    files:
      - file: houses.json
        label: Elenco Case
        name: houses
        fields:
          - label: Case
            name: items
            widget: list
            summary: "{{fields.code}} — {{fields.city}} ({{fields.street}} {{fields.number}}, {{fields.zip}})"
            fields:
              # Codice casa generato dallo script: nascosto ma obbligatorio
              - { label: "Codice casa", name: "code", widget: "hidden", required: true }

              # Indirizzo (obbligatori)
              - { label: "Regione",  name: "region",   widget: "string", required: true, hint: "Seleziona dal menu (con ricerca)" }
              - { label: "Città",    name: "city",     widget: "string", required: true, hint: "Cerca e seleziona dal menu" }
              - { label: "Provincia (2 lettere)", name: "province", widget: "string", required: true, hint: "Es. NU, MI, RM..." }
              - { label: "CAP",      name: "zip",      widget: "string", required: true }
              - { label: "Via",      name: "street",   widget: "string", required: true, hint: "Cerca e seleziona dal menu" }
              - { label: "Civico",   name: "number",   widget: "string", required: true, hint: "Puoi cercare/compilare" }

              # Proprietario (obbligatori)
              - { label: "Proprietario - Nome",    name: "owner_first", widget: "string", required: true }
              - { label: "Proprietario - Cognome", name: "owner_last",  widget: "string", required: true }
              - { label: "Proprietario - Data di nascita (dd/mm/yyyy)", name: "owner_birth", widget: "string", pattern: ["^\\d{2}/\\d{2}/\\d{4}$", "Usa il formato dd/mm/yyyy, es. 31/01/1980"], required: true }
              - { label: "Proprietario - Sesso", name: "owner_gender", widget: "select", options: ["M","F"], required: true }
              - { label: "Proprietario - Città di nascita", name: "owner_birth_city", widget: "string", required: true }
              - { label: "Proprietario - Provincia di nascita (2 lettere)", name: "owner_birth_prov", widget: "string", required: true }
              - { label: "Proprietario - Codice fiscale", name: "owner_cf", widget: "string", required: true, hint: "16 caratteri, es. RSSMRA80A01H501U" }

