backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: houses
    label: Case
    files:
      - file: "houses.json"
        label: "Elenco Case"
        name: "houses"
        fields:
          - label: "Case"
            name: "items"
            widget: "list"
            summary: "{{fields.code}} — {{fields.city}} ({{fields.street}} {{fields.number}}, {{fields.zip}})"
            fields:
              - label: "Codice casa"
                name: "code"
                widget: "string"
                required: false
                hint: "Generato automaticamente; non modificabile"

              - label: "Regione"
                name: "region"
                widget: "select"
                options:
                  - Abruzzo
                  - Basilicata
                  - Calabria
                  - Campania
                  - Emilia-Romagna
                  - Friuli-Venezia Giulia
                  - Lazio
                  - Liguria
                  - Lombardia
                  - Marche
                  - Molise
                  - Piemonte
                  - Puglia
                  - Sardegna
                  - Sicilia
                  - Toscana
                  - Trentino-Alto Adige
                  - Umbria
                  - Valle d'Aosta
                  - Veneto
                required: true

              - label: "Città"
                name: "city"
                widget: "string"
                required: true

              - label: "Provincia (2 lettere)"
                name: "province"
                widget: "string"
                required: true

              - label: "CAP"
                name: "zip"
                widget: "string"
                required: true

              - label: "Via/Piazza"
                name: "street"
                widget: "string"
                required: true

              - label: "Civico"
                name: "number"
                widget: "string"
                required: true

              - label: "Proprietario - Nome"
                name: "owner_first"
                widget: "string"
                required: true

              - label: "Proprietario - Cognome"
                name: "owner_last"
                widget: "string"
                required: true

              - label: "Proprietario - Data di nascita (dd/mm/yyyy)"
                name: "owner_birth"
                widget: "string"
                required: true
                pattern:
                  - '^\d{2}/\d{2}/\d{4}$'
                  - 'Formato: dd/mm/yyyy'

              - label: "Proprietario - Sesso"
                name: "owner_gender"
                widget: "select"
                options:
                  - M
                  - F
                required: true

              - label: "Proprietario - Città di nascita"
                name: "owner_birth_city"
                widget: "string"
                required: true

              - label: "Proprietario - Provincia di nascita (2 lettere)"
                name: "owner_birth_prov"
                widget: "string"
                required: true

              - label: "Proprietario - Codice fiscale"
                name: "owner_cf"
                widget: "string"
                required: true
                hint: "16 caratteri"
