backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "settings"
    label: "Impostazioni"
    files:
      - file: "settings.json"
        label: "Impostazioni generali"
        name: "settings"
        fields:
          - { label: "Tariffa standard (€/h)", name: "base_hourly_default", widget: "number", value_type: "float", min: 8, step: 0.5, default: 12 }
          - { label: "m² per 1 ora", name: "m2_per_hour", widget: "number", value_type: "int", min: 10, max: 200, step: 1, default: 35 }
          - { label: "Finestra offerte (ore)", name: "bid_window_hours", widget: "number", value_type: "int", min: 1, max: 72, step: 1, default: 12 }
          - { label: "Max offerte", name: "max_offers", widget: "number", value_type: "int", min: 1, max: 20, step: 1, default: 5 }
          - { label: "Email notifiche (prenotazioni/partner)", name: "notify_email", widget: "string", default: "alessandrospanu92@gmail.com" }

  - name: "partners"
    label: "Partner"
    files:
      - file: "partners.json"
        label: "Elenco Partner"
        name: "partners"
        fields:
          - label: "Partner"
            name: "items"
            widget: "list"
            summary: "{{fields.name}} — {{fields.address.city}} (raggio {{fields.radius_km}} km, €{{fields.rate_eur_h}}/h)"
            fields:
              - { label: "ID (facoltativo)", name: "id", widget: "string", required: false }
              - { label: "Nome e cognome", name: "name", widget: "string", required: true }
              - { label: "Email", name: "email", widget: "string", required: true }
              - { label: "Telefono", name: "phone", widget: "string", required: true }
              - label: "Indirizzo (domicilio)"
                name: "address"
                widget: "object"
                fields:
                  - { label: "Via/Piazza", name: "street", widget: "string", required: true }
                  - { label: "Civico", name: "number", widget: "string", required: true }
                  - { label: "CAP", name: "zip", widget: "string", required: true, pattern: ["^\\d{5}$", "Inserisci 5 cifre"] }
                  - { label: "Città", name: "city", widget: "string", required: true }
                  - { label: "Provincia (2 lettere)", name: "province", widget: "string", required: true }
                  - { label: "Regione", name: "region", widget: "string", required: true }
              - { label: "Raggio di lavoro (km)", name: "radius_km", widget: "number", value_type: "int", min: 5, max: 200, step: 1, default: 25 }
              - { label: "Tariffa oraria (€/h, min 8)", name: "rate_eur_h", widget: "number", value_type: "float", min: 8, step: 0.5, default: 12 }
              - { label: "Attivo", name: "active", widget: "boolean", default: true }
              - { label: "Latitudine (auto)", name: "lat", widget: "number", required: false }
              - { label: "Longitudine (auto)", name: "lon", widget: "number", required: false }
