# Forza la home sulla root del sito
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# (facoltativo) se vuoi che /home vada comunque alla home
[[redirects]]
  from = "/home"
  to = "/index.html"
  status = 301
