# ===========================
# Netlify configuration - B&B Clean
# ===========================

[build]
  publish = "."
  command = "" # statico; se hai un build step, impostalo qui

# ---------------------------
# Security & Performance (global)
# ---------------------------

# Header di sicurezza globali.
# NOTA: abilitiamo 'unsafe-inline' negli script perché usi script inline (es. in login.html).
# Se in futuro li sposti tutti in file separati, potremo restringere.
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=()"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    # CSP globale: consenti inline script e gli host di Auth0 + jsDelivr.
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' https://cdn.auth0.com https://cdn.jsdelivr.net;
      connect-src 'self' https://dev-nmvv4fpc7jmiw1pw.eu.auth0.com https://*.auth0.com;
      img-src 'self' data: blob:;
      style-src 'self' 'unsafe-inline';
      font-src 'self' data:;
      frame-src https://*.auth0.com;
      base-uri 'self';
      form-action 'self' https://*.auth0.com;
      object-src 'none';
      upgrade-insecure-requests;
    """

# Cache aggressiva per asset statici
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# ---------------------------
# Redirects (se NON usi l'omonimo file _redirects)
# ---------------------------
# Esempi: scommenta se vuoi gestirli qui invece che in _redirects.
# [[redirects]]
#   from = "/signup.html"
#   to = "/login.html?mode=signup"
#   status = 301
#
# [[redirects]]
#   from = "/iscrizione-cliente.html"
#   to = "/login.html?mode=signup"
#   status = 301
